apiVersion: apps/v1
kind: Deployment # Определение Deployment для приложения essay-app
metadata:
  name: essay-app-deploy # Имя Deployment для идентификации в кластере
  labels:
    app: essay-app-deploy # Метки для ассоциации с другими ресурсами
spec:
  replicas: 1 # Количество реплик пода, которые должны быть запущены
  selector: # Количество реплик пода, которые должны быть запущены
    matchLabels:
      project: essay-app
  # Шаблон для создания подов, включает метаданные и спецификации контейнеров
  template:
    metadata:
      labels:
        project: essay-app # Метки, ассоциированные с подом, соответствуют селектору выше
    spec:
      containers:
        - name: essay-app
          image: nochoooo/essay-app:v1 # Образ Docker, который будет использоваться для пода
          ports: # Список портов, которые контейнер будет прослушивать
            - containerPort: 5000
          envFrom:
            - configMapRef: # Определение переменных среды из ConfigMap
                # Имя ConfigMap, содержащего параметры подключения к базе данных
                name: postgres-db-config

---
apiVersion: v1
kind: Service # Определение Service для предоставления доступа к приложению essay-app
metadata:
  name: essay-app-service # Имя Service для идентификации в кластере
  labels:
    owner: nochoooo
spec:
  selector: # Селектор для определения, к каким подам должен обращаться Service
    project: essay-app
  ports:  # Список портов и протоколов, на которых Service будет доступен
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort